"""Static contract checks for tracked Oracle accounting bootstrap files."""

import re
from datetime import date
from decimal import Decimal
from pathlib import Path


ACCOUNTING_DIRECTORY = (
    Path(__file__).resolve().parents[1] / "database" / "accounting"
)


def _read(filename: str) -> str:
    return (ACCOUNTING_DIRECTORY / filename).read_text(encoding="utf-8")


def _compact(content: str) -> str:
    return re.sub(r"\s+", " ", content).lower()


def _without_sql_comments(content: str) -> str:
    return re.sub(r"--[^\n]*", "", content)


def _assert_no_destructive_statements(content: str) -> None:
    assert not re.search(
        r"\b(drop|truncate|delete|merge|alter)\b",
        content,
        flags=re.IGNORECASE,
    )


def _fixture_rows(seed: str, table_name: str) -> list[dict]:
    pattern = re.compile(
        rf"""
        INSERT\s+INTO\s+{re.escape(table_name)}\s*
        \((?P<columns>.*?)\)\s*
        VALUES\s*\((?P<values>.*?)\)\s*;
        """,
        flags=re.IGNORECASE | re.DOTALL | re.VERBOSE,
    )
    rows = []

    for match in pattern.finditer(_without_sql_comments(seed)):
        columns = [
            column.strip().lower()
            for column in match.group("columns").split(",")
        ]
        values = [
            value.strip()
            for value in match.group("values").split(",")
        ]
        assert len(columns) == len(values)
        rows.append(dict(zip(columns, values)))

    return rows


def _sql_value(value: str):
    if value == "NULL":
        return None
    if value.startswith("DATE '") and value.endswith("'"):
        return date.fromisoformat(value[6:-1])
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    return Decimal(value)


def _parsed_fixture_rows(seed: str, table_name: str) -> list[dict]:
    return [
        {
            column: _sql_value(value)
            for column, value in row.items()
        }
        for row in _fixture_rows(seed, table_name)
    ]


def test_schema_reproduces_the_accounting_table_contract():
    schema = _read("01_schema.sql")
    compact = _compact(schema)

    for table_name in (
        "accounting_categories",
        "financial_transactions",
        "bank_transactions",
        "audit_log",
    ):
        assert f"create table {table_name}" in compact

    assert compact.count("generated by default as identity") == 4
    for identity_option in ("start with 1", "increment by 1", "cache 20", "nocycle"):
        assert compact.count(identity_option) == 4
    for identity_column in (
        "accounting_category_id number generated by default as identity",
        "transaction_id number generated by default as identity",
        "bank_transaction_id number generated by default as identity",
        "audit_id number generated by default as identity",
    ):
        assert identity_column in compact

    for required_column in (
        "account_code varchar2(20) not null",
        "account_name varchar2(100) not null",
        "transaction_date date not null",
        "amount number(12,2) not null",
        "ai_confidence number(5,4)",
        "reference_number varchar2(100)",
        "match_confidence number(5,4)",
        "created_at timestamp(6) default current_timestamp not null",
    ):
        assert required_column in compact

    for constraint_name in (
        "pk_accounting_categories",
        "pk_financial_transactions",
        "pk_bank_transactions",
        "pk_audit_log",
        "uq_accounting_category_code",
        "fk_financial_transaction_accounting_category",
        "fk_bank_financial_transaction",
        "fk_audit_bank_transaction",
        "fk_audit_financial_transaction",
        "chk_financial_transaction_type",
        "chk_financial_transaction_status",
        "chk_reconciliation_status",
        "chk_ai_confidence",
        "chk_accounting_category_active",
        "chk_accounting_category_type",
        "chk_bank_transaction_status",
        "chk_bank_investigation_status",
    ):
        assert constraint_name in compact

    for required_value in (
        "'revenue'",
        "'expense'",
        "'cogs'",
        "'sale'",
        "'bank_fee'",
        "'pending'",
        "'posted'",
        "'unmatched'",
        "'matched'",
        "'investigated'",
    ):
        assert required_value in compact

    assert not re.search(
        r"check\s*\([^)]*\bmatch_type\b",
        schema,
        flags=re.IGNORECASE | re.DOTALL,
    )
    assert "create trigger" not in compact
    assert "create index" not in compact
    assert "iseq$$_" not in compact
    _assert_no_destructive_statements(schema)


def test_seed_is_bounded_synthetic_and_non_destructive():
    seed = _read("02_seed_demo.sql")
    compact = _compact(seed)

    assert len(re.findall(
        r"insert\s+into\s+accounting_categories\s*\(",
        seed,
        flags=re.IGNORECASE,
    )) == 8
    assert len(re.findall(
        r"insert\s+into\s+financial_transactions\s*\(",
        seed,
        flags=re.IGNORECASE,
    )) == 5
    assert len(re.findall(
        r"insert\s+into\s+bank_transactions\s*\(",
        seed,
        flags=re.IGNORECASE,
    )) == 4
    assert "insert into audit_log" not in compact

    for value in (
        "4000",
        "5000",
        "6100",
        "6200",
        "6300",
        "6400",
        "6500",
        "6600",
        "sales revenue",
        "cost of goods sold",
        "software",
        "office supplies",
        "bank fees",
        "travel",
        "advertising",
        "utilities",
        "microsoft 365",
        "950.00",
        "-129.00",
        "-96.00",
        "-3.50",
    ):
        assert value in compact

    assert "commit;" in compact
    _assert_no_destructive_statements(seed)


def test_financial_fixtures_preserve_identity_order_and_bookkeeping_totals():
    financial_rows = _parsed_fixture_rows(
        _read("02_seed_demo.sql"),
        "financial_transactions",
    )

    assert len(financial_rows) == 5
    assert financial_rows[4]["description"] == "Microsoft 365"
    assert financial_rows[4]["transaction_type"] == "EXPENSE"
    assert financial_rows[4]["status"] == "PENDING"

    posted_sales = sum(
        row["amount"]
        for row in financial_rows
        if row["transaction_type"] == "SALE"
        and row["status"] == "POSTED"
    )
    posted_expenses = sum(
        abs(row["amount"])
        for row in financial_rows
        if row["transaction_type"] in {"EXPENSE", "BANK_FEE"}
        and row["status"] == "POSTED"
    )
    posted_net_movement = sum(
        row["amount"]
        for row in financial_rows
        if row["status"] == "POSTED"
    )

    assert posted_sales == Decimal("950.00")
    assert posted_expenses == Decimal("228.50")
    assert posted_net_movement == Decimal("721.50")


def test_bank_fixtures_produce_the_expected_reconciliation_candidates():
    seed = _read("02_seed_demo.sql")
    financial_rows = _parsed_fixture_rows(seed, "financial_transactions")
    bank_rows = _parsed_fixture_rows(seed, "bank_transactions")

    assert len(financial_rows) == 5
    assert len(bank_rows) == 4

    candidate_ids_by_bank_id = {}
    date_difference_by_bank_id = {}

    for bank_id, bank_row in enumerate(bank_rows, start=1):
        candidates = [
            (financial_id, financial_row)
            for financial_id, financial_row in enumerate(
                financial_rows,
                start=1,
            )
            if financial_row["amount"] == bank_row["amount"]
            and abs(
                (financial_row["transaction_date"] - bank_row["transaction_date"])
                .days
            ) <= 2
        ]
        candidate_ids_by_bank_id[bank_id] = [
            financial_id
            for financial_id, _ in candidates
        ]
        date_difference_by_bank_id[bank_id] = [
            abs(
                (financial_row["transaction_date"] - bank_row["transaction_date"])
                .days
            )
            for _, financial_row in candidates
        ]

    assert candidate_ids_by_bank_id == {
        1: [3],
        2: [1],
        3: [],
        4: [5],
    }
    assert date_difference_by_bank_id == {
        1: [0],
        2: [0],
        3: [],
        4: [1],
    }


def test_reconciliation_procedure_preserves_current_contract_shape():
    procedure = _read("03_reconciliation.sql")
    compact = _compact(procedure)

    assert re.search(
        r"create\s+or\s+replace\s+procedure\s+reconcile_bank_transactions\s+as",
        procedure,
        flags=re.IGNORECASE,
    )
    for label in ("exact_match", "possible_match", "no_match"):
        assert label in compact
    for confidence in ("1.00", "0.90", "0.80", "then 0"):
        assert confidence in compact

    assert "select min(ft.transaction_id)" in compact
    assert "select count(*)" in compact
    assert "abs(ft.transaction_date - bank_tx.transaction_date) <= 2" in compact
    assert "ft.transaction_date = bank_tx.transaction_date" in compact
    assert "from bank_transactions where status = 'unmatched'" in compact
    assert re.search(
        r"status\s*=\s*case.*?"
        r"ft\.transaction_date\s*=\s*bank_tx\.transaction_date.*?"
        r"then\s*'matched'.*?else\s*'unmatched'",
        procedure,
        flags=re.IGNORECASE | re.DOTALL,
    )
    assert "commit;" in compact
    assert "create table" not in compact
    assert not re.search(r"\b(drop|truncate|delete|alter)\b", compact)


def test_install_script_has_the_required_fresh_schema_order():
    install = _read("00_install.sql")
    executable = _compact(_without_sql_comments(install))

    blank_lines_position = executable.index("set sqlblanklines on")
    fail_fast_position = executable.index(
        "whenever sqlerror exit sql.sqlcode rollback"
    )
    schema_position = executable.index("@@01_schema.sql")
    seed_position = executable.index("@@02_seed_demo.sql")
    procedure_position = executable.index("@@03_reconciliation.sql")

    assert (
        blank_lines_position
        < fail_fast_position
        < schema_position
        < seed_position
        < procedure_position
    )
