-- ============================================================
-- E-COMMERCE INTELLIGENCE PLATFORM
-- DATABASE SCHEMA
-- Oracle Database 26ai
-- ============================================================


-- ============================================================
-- 1. CUSTOMERS
-- ============================================================

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    country VARCHAR2(50) NOT NULL,
    age NUMBER(3),

    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT chk_customers_age CHECK (age >= 18)
);


-- ============================================================
-- 2. CATEGORIES
-- ============================================================

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT uq_categories_name UNIQUE (category_name)
);


-- ============================================================
-- 3. SUPPLIERS
-- ============================================================

CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_name VARCHAR2(100) NOT NULL,
    country VARCHAR2(50) NOT NULL,
    contact_email VARCHAR2(100),

    CONSTRAINT pk_suppliers PRIMARY KEY (supplier_id),
    CONSTRAINT uq_supplier_email UNIQUE (contact_email)
);


-- ============================================================
-- 4. PRODUCTS
-- ============================================================

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR2(150) NOT NULL,
    category_id NUMBER NOT NULL,
    supplier_id NUMBER NOT NULL,
    price NUMBER(10,2) NOT NULL,
    cost_price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER NOT NULL,
    last_updated DATE,

    CONSTRAINT pk_products PRIMARY KEY (product_id),

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT chk_products_price
        CHECK (price >= 0),

    CONSTRAINT chk_products_cost
        CHECK (cost_price >= 0),

    CONSTRAINT chk_products_stock
        CHECK (stock_quantity >= 0)
);


-- ============================================================
-- 5. ORDERS
-- ============================================================

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_orders PRIMARY KEY (order_id),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT chk_orders_status
        CHECK (
            status IN (
                'PENDING',
                'SHIPPED',
                'COMPLETED',
                'CANCELLED'
            )
        )
);


-- ============================================================
-- 6. ORDER_ITEMS
-- ============================================================

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_items_price
        CHECK (unit_price >= 0)
);


-- ============================================================
-- 7. PAYMENTS
-- ============================================================

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    payment_method VARCHAR2(20) NOT NULL,
    payment_status VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_payments PRIMARY KEY (payment_id),

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT chk_payment_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payment_method
        CHECK (
            payment_method IN (
                'CARD',
                'PAYPAL',
                'BANK_TRANSFER'
            )
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'PAID',
                'FAILED',
                'REFUNDED'
            )
        )
);


-- ============================================================
-- 8. REVIEWS
-- ============================================================

CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    rating NUMBER(1) NOT NULL,
    review_text VARCHAR2(500),
    review_date DATE NOT NULL,

    CONSTRAINT pk_reviews PRIMARY KEY (review_id),

    CONSTRAINT fk_reviews_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT chk_reviews_rating
        CHECK (rating BETWEEN 1 AND 5)
);


-- ============================================================
-- 9. DISCOUNTS
-- ============================================================

CREATE TABLE discounts (
    discount_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER NOT NULL,
    discount_percent NUMBER(5,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    CONSTRAINT pk_discounts PRIMARY KEY (discount_id),

    CONSTRAINT fk_discounts_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT chk_discount_percent
        CHECK (discount_percent BETWEEN 0 AND 100),

    CONSTRAINT chk_discount_dates
        CHECK (end_date >= start_date)
);


-- ============================================================
-- 10. DEPARTMENTS
-- ============================================================

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT uq_department_name UNIQUE (department_name)
);


-- ============================================================
-- 11. EMPLOYEES
-- ============================================================

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    department_id NUMBER NOT NULL,
    manager_id NUMBER,
    hire_date DATE NOT NULL,
    salary NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_employees PRIMARY KEY (employee_id),

    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id),

    CONSTRAINT fk_employees_manager
        FOREIGN KEY (manager_id)
        REFERENCES employees(employee_id),

    CONSTRAINT chk_employee_salary
        CHECK (salary >= 0)
);