-- Oracle Accounting Bootstrap Schema
-- This reproduces the current accounting/reconciliation structure.

CREATE TABLE accounting_categories (
    accounting_category_id NUMBER GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        CACHE 20
        NOCYCLE
    ),
    account_code VARCHAR2(20) NOT NULL,
    account_name VARCHAR2(100) NOT NULL,
    account_type VARCHAR2(20) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_accounting_categories
        PRIMARY KEY (accounting_category_id),
    CONSTRAINT uq_accounting_category_code
        UNIQUE (account_code),
    CONSTRAINT chk_accounting_category_active
        CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_accounting_category_type
        CHECK (
            account_type IN (
                'REVENUE',
                'EXPENSE',
                'COGS',
                'ASSET',
                'LIABILITY',
                'EQUITY'
            )
        )
);


CREATE TABLE financial_transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        CACHE 20
        NOCYCLE
    ),
    transaction_date DATE NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL,
    description VARCHAR2(200),
    amount NUMBER(12,2) NOT NULL,
    category VARCHAR2(100),
    vendor VARCHAR2(150),
    status VARCHAR2(20) DEFAULT 'POSTED' NOT NULL,
    ai_suggested_category VARCHAR2(100),
    ai_confidence NUMBER(5,4),
    reconciliation_status VARCHAR2(20) DEFAULT 'UNMATCHED' NOT NULL,
    original_ai_category VARCHAR2(100),
    original_ai_confidence NUMBER(5,4),
    accounting_category_id NUMBER,

    CONSTRAINT pk_financial_transactions
        PRIMARY KEY (transaction_id),
    CONSTRAINT fk_financial_transaction_accounting_category
        FOREIGN KEY (accounting_category_id)
        REFERENCES accounting_categories(accounting_category_id),
    CONSTRAINT chk_financial_transaction_type
        CHECK (
            transaction_type IN (
                'SALE',
                'EXPENSE',
                'BANK_FEE',
                'REFUND',
                'ADJUSTMENT'
            )
        ),
    CONSTRAINT chk_financial_transaction_status
        CHECK (status IN ('PENDING', 'POSTED')),
    CONSTRAINT chk_ai_confidence
        CHECK (
            ai_confidence IS NULL
            OR (ai_confidence >= 0 AND ai_confidence <= 1)
        ),
    CONSTRAINT chk_reconciliation_status
        CHECK (reconciliation_status IN ('UNMATCHED', 'MATCHED'))
);


CREATE TABLE bank_transactions (
    bank_transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        CACHE 20
        NOCYCLE
    ),
    transaction_date DATE NOT NULL,
    description VARCHAR2(200),
    amount NUMBER(12,2) NOT NULL,
    reference_number VARCHAR2(100),
    status VARCHAR2(20) DEFAULT 'UNMATCHED' NOT NULL,
    financial_transaction_id NUMBER,
    match_type VARCHAR2(20),
    match_confidence NUMBER(5,4),
    investigation_status VARCHAR2(20),

    CONSTRAINT pk_bank_transactions
        PRIMARY KEY (bank_transaction_id),
    CONSTRAINT fk_bank_financial_transaction
        FOREIGN KEY (financial_transaction_id)
        REFERENCES financial_transactions(transaction_id),
    CONSTRAINT chk_bank_transaction_status
        CHECK (status IN ('UNMATCHED', 'MATCHED')),
    CONSTRAINT chk_bank_investigation_status
        CHECK (
            investigation_status IS NULL
            OR investigation_status = 'INVESTIGATED'
        )
);


CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        CACHE 20
        NOCYCLE
    ),
    bank_transaction_id NUMBER,
    financial_transaction_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    details VARCHAR2(500),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_log
        PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_bank_transaction
        FOREIGN KEY (bank_transaction_id)
        REFERENCES bank_transactions(bank_transaction_id),
    CONSTRAINT fk_audit_financial_transaction
        FOREIGN KEY (financial_transaction_id)
        REFERENCES financial_transactions(transaction_id)
);
